# Hadolint configuration
failure-threshold: warning
ignored:
  - DL3008
  - DL3013
  - DL3042

format: tty
no-color: false

override:
  error:
    - DL3003
    - DL3006
    - DL3007
    - DL3015
    - DL3025
    - DL3059
